spring:
  application:
    name: logInjector
  rabbitmq:
    addresses: localhost:5672
server:
  port: 3000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    dbOperation: dpOperation.queue
  routing-keys:
    internal-dpOperation: internal.dpOperation.routing-key